export const insults = [
  "On s'en branle, on s'en branle, on s'en branle.",
  "Ta gueule avec ta CX",
  "Oui c'est bien, allez ta gueule avec ta CX",
  "Chut chut, chuuuuuuut.",
  "Stoooooooooooooop",
  "Ça part sur un mute hein ?",
  "Va plutôt faire la carte grise au lieu de nous casser les couilles",
  "Euh, ta gueule pour voir ?",
  "C'était mieux quand t'étais mute",
];

export const randomReplies = [
  "Ouais fin raconte pas ta vie",
  "Ok tamere",
  "Manje moi lpoiro",
  "Sayer frr ftg",
  "Eh gros sayer",
  "On a déjà entendu cette histoire 40 fois.",
  "Les femmes te disent la même chose ?",
  "Quel est le rapport avec les Juifs ?",
  "Mais, du coup , t'as voté Marcon ?",
  "EH BEN MOI UNE FOIS J'AI PISSÉ PAR LA FENÊTRE",
  "Mais ma parole vous êtes beuré vous aussi.",
  "Qui s'en fout ?",
  "Ta geule ?",
  "Mais meeeeeerde",
  "T'as essayer de fermer ta gueule ?",
  "T'es le roi des cons au pays des emmerdeurs !",
  "Nikoumouk !",
  "Le jour où on mettra des cons sur orbite, t'as pas fini de tourner !",
  "Ta mère elle boit de la Kro.",
  "Dégage avec ta merde",
  "MICRON DÉMISSION !!!!!!",
  "T'est tendue Natasha.",
  "T'as été adopté",
  "arrête.",
  "cesse.",
  "D'après le revue technique de la FZR1000, je m'en bats les couilles",
  "Répète, qu'on s'en re-batte les couilles",
  "Pourtant j'en ai entendu des conneries aujourd'hui",
  "Alors les bavaroises, on se prend pour Schumacker ?",
];

export const bastianoQuotes = [
  "Attitude inébranlable, mais branle moi quand même",
  "La barquette c'est pour l'asso, la quequette c'est pour Anne-So",
  "Le mulet ça revient. Pas comme ma femme...",
  "Je bande en haut débit",
  "Le kiff n'est plus là",
  "Les pick-ups avant les pin-ups",
  "Increvable, comme ma bite",
  "Hybride moi les couilles",
  "Pissez pas dans l'eau, ça étrangle les dauphins",
  "Ton fion illumine mes nuits tumultueuses",
  "En route vers ton cul",
  "Zig zig, zigounette au vent",
  "Deux doigts sur la trois voies, elle est restée sans voix",
  "T'es pas aussi chaude que ma BX",
  "Nature, peinture, on bandera dans la confiture",
  "Des bisous du Futuroscope, on a pris le futur en stop",
  "Tu as tout mon soutien, et mon soutien-gorge aussi",
  "Sans tabou, mais avec du taboulet",
  "Là je bante, j'te raconte pas",
];

export const errorMessage = process.env.ERROR_MESSAGE;
